spring.application.name=gestionstage

# Connexion à la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gestionstage
spring.datasource.username=postgres
spring.datasource.password=codegode

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true